sudo: false

language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

before_script:
  - if [[ ${TRAVIS_RUST_VERSION} != nightly ]]; then
      rustup component add rustfmt;
    fi
  - if [[ ${TRAVIS_RUST_VERSION} == stable ]]; then
      rustup component add clippy;
    fi

script:
  - cargo fmt -- --check
  - cargo test
  - if [[ ${TRAVIS_RUST_VERSION} == stable ]]; then
      cargo clippy --all-targets -- --deny clippy::all;
    fi
